/**:
  ros__parameters:
    common:
      # 改成你 Go2 上已经在用的 topic
      lid_topic: "/SMX/Go2Lidar"      # 对应 Cartographer 里的 points2
      imu_topic: "/SMX/Go2IMU"        # 对应 Cartographer 里的 imu
      con_frame: false                # 先不拼多帧
      con_frame_num: 1
      cut_frame: false
      cut_frame_time_interval: 0.1
      time_lag_imu_to_lidar: 0.0      # 先假设 IMU 与 LiDAR 已经时间对齐

    preprocess:
      lidar_type: 5                   # 保持 L1/L2 类型
      scan_line: 72                   # L1 = 18 线
      # Go2Lidar 点云里 PointField "time" 的单位：
      # - 如果是“秒”，保持 0
      # - 如果是“微秒”，改成 2
      timestamp_unit: 0               # 0-second, 1-ms, 2-us, 3-ns
      blind: 0.5                      # = Cartographer 的 min_range = 0.5

    mapping:
      imu_en: true
      start_in_aggressive_motion: false
      extrinsic_est_en: false
      imu_time_inte: 0.003

      satu_acc: 30.0
      satu_gyro: 35.0
      acc_norm: 9.81
      lidar_meas_cov: 0.01
      acc_cov_output: 500.0
      gyr_cov_output: 1000.0
      b_acc_cov: 0.0001 
      b_gyr_cov: 0.0001 
      imu_meas_acc_cov: 0.1
      imu_meas_omg_cov: 0.1
      gyr_cov_input: 0.01
      acc_cov_input: 0.1

      plane_thr: 0.1
      match_s: 81.0
      fov_degree: 180.0
      det_range: 30.0

      gravity_align: true
      gravity:      [0.0, 0.0, -9.810]
      gravity_init: [0.0, 0.0, -9.810]

      # ===== 这里改成和 FAST-LIO2 一致 =====
      # LiDAR 在 IMU（base_imu）坐标系下的位姿
      extrinsic_T: [0.31502, 0.0, -0.089145]
      extrinsic_R: [
        -0.965512, 0.0,       0.260358,
         0.0,      1.0,       0.0,
        -0.260358, 0.0,      -0.965512
      ]

    odometry: 
      publish_odometry_without_downsample: true  

    publish:
      path_en: true                 # 发布路径，RViz 能看到轨迹
      scan_publish_en: true         # 发布去畸变后的点云
      scan_bodyframe_pub_en: true   # 是否在 IMU（body）frame 下发布点云

    pcd_save:
      pcd_save_en: true             # 建完图后可以保存 PCD
      interval: -1                  # -1 = 所有帧存到一个 PCD
